# Generated by Django 5.0.1 on 2024-02-18 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine_id', models.CharField(max_length=100)),
                ('Medicine_Name', models.CharField(max_length=100)),
                ('Batch_No', models.CharField(max_length=100)),
                ('Medicine_Used', models.CharField(max_length=100)),
                ('Manifacture_Date', models.DateField(max_length=100)),
                ('Expiring_Date', models.DateField(max_length=100)),
                ('Maximum_Retail_prise', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qrcodes')),
            ],
        ),
        migrations.CreateModel(
            name='firm_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('user_type', models.CharField(max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
